import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsInt, Min, Max, IsEnum, IsOptional, IsUUID } from 'class-validator';

import { TransactionType } from '@shared/enums';
import { IsInTimestampRange, IsIsoInstant } from '@shared/decorators/is-iso-date.decorator';
import { IsMoneyAmount } from '@shared/decorators/is-money-amount.decorator';
import { IsDescription, IsNotInFuture, IsPositiveAmount } from './transaction-field.decorators';

// Swagger metadata is explicit: tests build the document without the CLI plugin.
export class CreateTransactionDto {
  @ApiProperty({ type: 'integer', example: 7, description: 'An active wallet of the space.' })
  @IsNotEmpty()
  @IsInt()
  @Min(1)
  @Max(2147483647)
  wallet_id!: number;

  @ApiProperty({
    type: 'integer',
    example: 12,
    description: 'An active, non-system category of the space whose type is transaction_type.',
  })
  @IsNotEmpty()
  @IsInt()
  @Min(1)
  @Max(2147483647)
  category_id!: number;

  @ApiProperty({ enum: TransactionType, enumName: 'TransactionType' })
  @IsNotEmpty()
  @IsEnum(TransactionType)
  transaction_type!: TransactionType;

  @ApiProperty({ example: '12.30', description: 'Decimal string, 0.01 to 99999999.99, at most 2 decimals.' })
  @IsNotEmpty()
  @IsMoneyAmount()
  @IsPositiveAmount()
  amount!: string;

  @ApiProperty({
    example: '2026-09-15T10:00:00.000Z',
    description: 'An instant with Z or a UTC offset, at most 60 s ahead of the server.',
  })
  @IsNotEmpty()
  @IsIsoInstant()
  @IsInTimestampRange()
  @IsNotInFuture()
  timestamp!: string;

  @ApiPropertyOptional({
    type: String,
    nullable: true,
    maxLength: 140,
    example: 'Lunch',
    description: 'Trimmed; blank or null means none.',
  })
  @IsDescription()
  description?: string | null;

  @ApiPropertyOptional({
    format: 'uuid',
    example: '0f8e3b1c-5d2a-4e8f-9a61-2c7d4b5e6f70',
    description:
      'Generated by the client once per user action and kept for its retries. Unique in the space: a create ' +
      'with a used id is refused, and GET /transactions/operations/:id tells what became of it.',
  })
  @IsOptional()
  @IsUUID()
  client_operation_id?: string;
}
